version: '3'

services:
  db:
    image: mysql/mysql-server:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trackorjargh
    command: mysqld --lower_case_table_names=1
  trackorjargh-application:
    image: trackorjargh-spring
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    ports:
      - 8443:8443
